Console.Write('H');
Console.Write('e');
Console.Write('l');
Console.Write('l');
Console.Write('o');
Console.Write(',');
Console.Write(' ');
Console.Write('W');
Console.Write('o');
Console.Write('r');
Console.Write('l');
Console.Write('d');
Console.Write('!');
